const events = [
  {
    id: 1,
    name: "ملتقى الابتكار والتكنولوجيا لطلاب كلية الهندسة جامعة القاهرة دفعة 2025",
    place: "معرض الفنون في بيروت، لبنان",
    time: "10:00 مساءً - 11:30 مساءً",
    date: "15 أغسطس 2025",
    status: "upcoming",
    users: [
      "https://i.ibb.co/KDxymfX/user1.png",
      "https://i.ibb.co/Hz1HmtT/user2.png",
      "https://i.ibb.co/phxqm7r/user3.png",
      "https://i.ibb.co/TH9fYPh/user4.png",
      "https://i.ibb.co/KDxymfX/user1.png",
    ],
    mainImg: "",

    images: [],
    video: "",
  },
  {
    id: 2,
    name: "ملتقى الشباب الرواد في ريادة الأعمال لطلاب كلية الاقتصاد جامعة القاهرة دفعة 2023",
    place: "مهرجان الموسيقى في دبي، الإمارات",
    time: "09:15 مساءً - 10:45 مساءً",
    date: "14 أغسطس 2023",
    status: "ended",
    users: [],
    mainImg: "https://i.ibb.co/ccgr4sL/party1.png",

    images: [
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
      "https://i.ibb.co/7R8wHZf/low-angle-graduated-students-1.png",
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
    ],
    video: "https://i.ibb.co/KmJ3fM0/unsplash-hzgs56-Ze49s.png",
  },
  {
    id: 3,
    name: "ندوة الطب البيطري المتقدمة لطلاب كلية الطب البيطري جامعة مدينة السادات دفعة 2026",
    place: "ورشة الأفلام القصيرة في الرباط، المغرب",
    time: "08:30 مساءً - 10:00 مساءً",
    date: "12 أغسطس 2026",
    status: "upcoming",
    users: [
      "https://i.ibb.co/KDxymfX/user1.png",
      "https://i.ibb.co/Hz1HmtT/user2.png",
      "https://i.ibb.co/phxqm7r/user3.png",
      "https://i.ibb.co/TH9fYPh/user4.png",
      "https://i.ibb.co/KDxymfX/user1.png",
    ],
    mainImg: "",
    images: [],
    video: "",
  },
  {
    id: 4,
    name: "حفل تخرج العلوم الإنسانية لطلاب كلية الآداب جامعة المنصورة دفعة 2022",
    place: "ندوة الأدب العربي في بغداد، العراق",
    time: "07:45 مساءً - 09:15 مساءً",
    date: "11 أغسطس 2022",
    status: "ended",
    users: [],
    mainImg: "https://i.ibb.co/v3XwqGL/party2.png",
    images: [
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
      "https://i.ibb.co/7R8wHZf/low-angle-graduated-students-1.png",
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
    ],
    video: "https://i.ibb.co/KmJ3fM0/unsplash-hzgs56-Ze49s.png",
  },
  {
    id: 5,
    name: "مؤتمر الأعمال الدولي لطلاب كلية التجارة جامعة الأهرامات دفعة 2027",
    place: "ملتقى التصميم الجرافيكي في الدوحة، قطر",
    time: "07:00 مساءً - 08:30 مساءً",
    date: "10 أغسطس 2027",
    status: "upcoming",
    users: [
      "https://i.ibb.co/KDxymfX/user1.png",
      "https://i.ibb.co/Hz1HmtT/user2.png",
      "https://i.ibb.co/phxqm7r/user3.png",
      "https://i.ibb.co/TH9fYPh/user4.png",
      "https://i.ibb.co/KDxymfX/user1.png",
    ],
    mainImg: "",
    images: [],
    video: "",
  },
  {
    id: 6,
    name: "ندوة العلوم السياسية الدولية لطلاب كلية العلوم السياسية جامعة الزقازيق دفعة 2024",
    place: "حفل الرقص التقليدي في تونس، تونس",
    time: "06:15 مساءً - 07:45 مساءً",
    date: "9 أغسطس 2024",
    status: "ended",
    users: [],
    mainImg: "https://i.ibb.co/hZt4SfL/party3.png",
    images: [
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
      "https://i.ibb.co/7R8wHZf/low-angle-graduated-students-1.png",
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
    ],
    video: "https://i.ibb.co/KmJ3fM0/unsplash-hzgs56-Ze49s.png",
  },
  {
    id: 7,
    name: "حفل تكريم العلماء  في مجال الفيزياء النووية جامعة الإسكندرية دفعة 2028",
    place: "مؤتمر العلوم الطبية في الكويت، الكويت",
    time: "05:30 مساءً - 07:00 مساءً",
    date: "8 أغسطس 2028",
    status: "upcoming",
    users: [
      "https://i.ibb.co/KDxymfX/user1.png",
      "https://i.ibb.co/Hz1HmtT/user2.png",
      "https://i.ibb.co/phxqm7r/user3.png",
      "https://i.ibb.co/TH9fYPh/user4.png",
      "https://i.ibb.co/KDxymfX/user1.png",
    ],
    mainImg: "",
    images: [],
    video: "",
  },
  {
    id: 8,
    name: "مؤتمر الطب الباطني والجراحة لطلاب كلية الطب جامعة عين شمس دفعة 2023",
    place: "ورشة الشعر في الجزائر، الجزائر",
    time: "04:45 مساءً - 06:15 مساءً",
    date: "7 أغسطس 2023",
    status: "ended",
    users: [],
    mainImg: "https://i.ibb.co/FW1SF6C/party4.png",
    images: [
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
      "https://i.ibb.co/7R8wHZf/low-angle-graduated-students-1.png",
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
    ],
    video: "https://i.ibb.co/KmJ3fM0/unsplash-hzgs56-Ze49s.png",
  },
  {
    id: 9,
    name: "ملتقى الثقافات العالمية لطلاب كلية الآداب والعلوم الاجتماعية جامعة حلوان دفعة 2029",
    place: "ملتقى الثقافة الإسلامية في اسطنبول، تركيا",
    time: "04:00 مساءً - 05:30 مساءً",
    date: "6 أغسطس 2029",
    status: "upcoming",
    users: [
      "https://i.ibb.co/KDxymfX/user1.png",
      "https://i.ibb.co/Hz1HmtT/user2.png",
      "https://i.ibb.co/phxqm7r/user3.png",
      "https://i.ibb.co/TH9fYPh/user4.png",
      "https://i.ibb.co/KDxymfX/user1.png",
    ],
    mainImg: "",
    images: [],
    video: "",
  },
  {
    id: 10,
    name: "حفل توزيع الجوائز للطلاب المتميزين في الرياضيات والفيزياء جامعة الإسكندرية دفعة 2024",
    place: "حفل التمثيل المسرحي في عمان، الأردن",
    time: "03:15 مساءً - 04:45 مساءً",
    date: "5 أغسطس 2024",
    status: "ended",
    users: [],
    mainImg: "https://i.ibb.co/ccgr4sL/party1.png",
    images: [
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
      "https://i.ibb.co/7R8wHZf/low-angle-graduated-students-1.png",
      "https://i.ibb.co/X5FSCTF/party-audience-on-spotlight-background-2107-2.png",
      "https://i.ibb.co/HtJXkGC/7452-3.png",
    ],
    video: "https://i.ibb.co/KmJ3fM0/unsplash-hzgs56-Ze49s.png",
  },
];

// https://www.npoint.io/docs/a02d1c3cc488817931a6
// https://api.npoint.io/a02d1c3cc488817931a6

let persons = [
  {
    id: "1",
    name: {
      arabic: "أحمد محمد",
      english: "Ahmed Mohamed",
    },
    image: "https://i.ibb.co/8rC1tR9/team-03.png",
    email: "ahmed@gmail.com",
    phone: "01012345678",
    age: 25,
  },
  {
    id: "2",
    name: {
      arabic: "سارة أحمد",
      english: "Sara Ahmed",
    },
    image: "https://i.ibb.co/w0gWdrt/team-05.png",
    email: "sara@gmail.com",
    phone: "01123456789",
    age: 30,
  },
  {
    id: "3",
    name: {
      arabic: "محمد علي",
      english: "Mohamed Ali",
    },
    image: "https://i.ibb.co/Wy24WbM/userm.png",
    email: "mohamed@gmail.com",
    phone: "01234567890",
    age: 28,
  },
  {
    id: "4",
    name: {
      arabic: "نورا خالد",
      english: "Nora Khaled",
    },
    image: "https://i.ibb.co/7YnT4p8/team-04.png",
    email: "nora@gmail.com",
    phone: "01345678901",
    age: 35,
  },
  {
    id: "5",
    name: {
      arabic: "لينا علي",
      english: "Lina Ali",
    },
    image: "https://i.ibb.co/9vXfcQV/userb.png",
    email: "lina@gmail.com",
    phone: "01456789012",
    age: 22,
  },
  {
    id: "6",
    name: {
      arabic: "يوسف حسن",
      english: "Youssef Hassan",
    },
    image: "https://i.ibb.co/25VqGK8/userc.png",
    email: "youssef@gmail.com",
    phone: "01567890123",
    age: 40,
  },
  {
    id: "7",
    name: {
      arabic: "رنا أحمد",
      english: "Rana Ahmed",
    },
    image: "https://i.ibb.co/QKP6rFM/usera.png",
    email: "rana@gmail.com",
    phone: "01678901234",
    age: 27,
  },
  {
    id: "8",
    name: {
      arabic: "مريم عمر",
      english: "Mariam Omar",
    },
    image: "https://i.ibb.co/w0gWdrt/team-05.png",
    email: "mariam@gmail.com",
    phone: "01789012345",
    age: 32,
  },
  {
    id: "9",
    name: {
      arabic: "علي حسين",
      english: "Ali Hussein",
    },
    image: "https://i.ibb.co/8rC1tR9/team-03.png",
    email: "ali@gmail.com",
    phone: "01890123456",
    age: 29,
  },
  {
    id: "10",
    name: {
      arabic: "سلمى مصطفى",
      english: "Salma Mustafa",
    },
    image: "https://i.ibb.co/7YnT4p8/team-04.png",
    email: "salma@gmail.com",
    phone: "01901234567",
    age: 33,
  },
];
// https://www.npoint.io/docs/020cb3bcb198f0b39ee0
// https://api.npoint.io/020cb3bcb198f0b39ee0

const items = [
  {
    id: 1,
    img: "https://i.ibb.co/zP4mnQg/stand.png",
    name: "ستاند اب",
  },
  {
    id: 2,
    img: "https://i.ibb.co/T2JKxLj/graduation.png",
    name: "حفلات تخرج",
  },
  {
    id: 3,
    img: "https://i.ibb.co/pnVcY80/Singing.png",
    name: "حفلات غناء",
  },
  {
    id: 4,
    img: "https://i.ibb.co/h19sWtS/fun.png",
    name: "حفلات فان داي",
  },
  {
    id: 5,
    img: "https://i.ibb.co/BPwBKFk/bazaar.png",
    name: "بازار",
  },
  {
    id: 6,
    img: "https://i.ibb.co/HzMFzqg/conferences.png",
    name: "مؤتمرات",
  },
];
// https://api.npoint.io/3499a5d9ee6a5ea8b7d0
// https://www.npoint.io/docs/3499a5d9ee6a5ea8b7d0

const eventss = [
  {
    id: 1,
    type: "حفلات تخرج",
    parties: [
      {
        id_party: 1,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 2,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 3,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 4,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 5,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 6,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 7,
        type_party: "حفلات تخرج",
        name_party: "Graduation Party",
        date_party: "الاثنين، 16 أغسطس 2024",
        location_party: "روما، إيطاليا",
        time_party: "7:00 مساءً",
        img_party: "https://i.ibb.co/v3XwqGL/party2.png",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    type: "حفلات غناء",
    parties: [
      {
        id_party: 1,
        type_party: "حفلات غناء",
        name_party: "Music Concert",
        date_party: "الثلاثاء، 17 أغسطس 2024",
        location_party: "باريس، فرنسا",
        time_party: "8:00 مساءً",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 2,
        type_party: "حفلات غناء",
        name_party: "Music Concert",
        date_party: "الثلاثاء، 17 أغسطس 2024",
        location_party: "باريس، فرنسا",
        time_party: "8:00 مساءً",
        users_party: [
          {
            id_user: 1,
            name_user: "سلمى محمود إبراهيم",
            email_user: "SalmaaAhmed12@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة كلية علوم",
            cost_user: 1000,
            seat_user: 5,
            idTicket_user: 220002203,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },

          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
      {
        id_party: 3,
        type_party: "حفلات غناء",
        name_party: "Music Concert",
        date_party: "الثلاثاء، 17 أغسطس 2024",
        location_party: "باريس، فرنسا",
        time_party: "8:00 مساءً",
        users_party: [
          {
            id_user: 2,
            name_user: "عبد الرحمن أحمد",
            email_user: "abdulrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1200,
            seat_user: 7,
            idTicket_user: 220002204,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 6,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 3,
            name_user: "أحمد محمد",
            email_user: "ahmed.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 6,
            idTicket_user: 220002205,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 4,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 4,
            name_user: "نورا يوسف",
            email_user: "nora.youssef@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الطب",
            cost_user: 1050,
            seat_user: 3,
            idTicket_user: 220002206,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 5,
            name_user: "يوسف علي",
            email_user: "youssef.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة العلوم السياسية",
            cost_user: 950,
            seat_user: 9,
            idTicket_user: 220002207,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 6,
            name_user: "ليلى أحمد",
            email_user: "laila.ahmed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفنون",
            cost_user: 1150,
            seat_user: 10,
            idTicket_user: 220002208,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 7,
            name_user: "محمود عبد الرحمن",
            email_user: "mahmoud.abdelrahman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الصيدلة",
            cost_user: 900,
            seat_user: 8,
            idTicket_user: 220002209,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 7,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 8,
            name_user: "مريم محمد",
            email_user: "maryam.mohamed@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الهندسة المعمارية",
            cost_user: 1000,
            seat_user: 2,
            idTicket_user: 220002210,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 3,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 9,
            name_user: "أميرة علي",
            email_user: "amira.ali@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الرياضيات",
            cost_user: 850,
            seat_user: 4,
            idTicket_user: 220002211,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 5,
            date_user: "الاثنين، 16 أغسطس",
          },
          {
            id_user: 10,
            name_user: "أحمد أيمن",
            email_user: "ahmed.ayman@gmail.com",
            image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
            party_user: "حفلة الفيزياء",
            cost_user: 1100,
            seat_user: 1,
            idTicket_user: 220002212,
            location_user: "روما، إيطاليا",
            numberOfCompanions_user: 2,
            date_user: "الاثنين، 16 أغسطس",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    type: "حفلات تخرج",
    parties: {
      id_party: 3,
      type_party: "مؤتمرات",
      name_party: "Tech Conference",
      date_party: "الأربعاء، 18 أغسطس 2024",
      location_party: "برلين، ألمانيا",
      time_party: "9:00 صباحًا",
      users_party: [
        {
          id_user: 1,
          name_user: "سلمى محمود إبراهيم",
          email_user: "SalmaaAhmed12@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة كلية علوم",
          cost_user: 1000,
          seat_user: 5,
          idTicket_user: 220002203,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 2,
          name_user: "عبد الرحمن أحمد",
          email_user: "abdulrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1200,
          seat_user: 7,
          idTicket_user: 220002204,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 6,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 3,
          name_user: "أحمد محمد",
          email_user: "ahmed.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 6,
          idTicket_user: 220002205,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 4,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 4,
          name_user: "نورا يوسف",
          email_user: "nora.youssef@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1050,
          seat_user: 3,
          idTicket_user: 220002206,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 5,
          name_user: "يوسف علي",
          email_user: "youssef.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة العلوم السياسية",
          cost_user: 950,
          seat_user: 9,
          idTicket_user: 220002207,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 6,
          name_user: "ليلى أحمد",
          email_user: "laila.ahmed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفنون",
          cost_user: 1150,
          seat_user: 10,
          idTicket_user: 220002208,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 7,
          name_user: "محمود عبد الرحمن",
          email_user: "mahmoud.abdelrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الصيدلة",
          cost_user: 900,
          seat_user: 8,
          idTicket_user: 220002209,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 7,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 8,
          name_user: "مريم محمد",
          email_user: "maryam.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الهندسة المعمارية",
          cost_user: 1000,
          seat_user: 2,
          idTicket_user: 220002210,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 9,
          name_user: "أميرة علي",
          email_user: "amira.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الرياضيات",
          cost_user: 850,
          seat_user: 4,
          idTicket_user: 220002211,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 10,
          name_user: "أحمد أيمن",
          email_user: "ahmed.ayman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 1,
          idTicket_user: 220002212,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
      ],
    },
  },
  {
    id: 4,
    type: "حفلات تخرج",
    parties: {
      id_party: 4,
      type_party: "ستاند اب",
      name_party: "Stand-Up Comedy Night",
      date_party: "الخميس، 19 أغسطس 2024",
      location_party: "نيويورك، الولايات المتحدة",
      time_party: "10:00 مساءً",
      users_party: [
        {
          id_user: 1,
          name_user: "سلمى محمود إبراهيم",
          email_user: "SalmaaAhmed12@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة كلية علوم",
          cost_user: 1000,
          seat_user: 5,
          idTicket_user: 220002203,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 2,
          name_user: "عبد الرحمن أحمد",
          email_user: "abdulrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1200,
          seat_user: 7,
          idTicket_user: 220002204,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 6,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 3,
          name_user: "أحمد محمد",
          email_user: "ahmed.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 6,
          idTicket_user: 220002205,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 4,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 4,
          name_user: "نورا يوسف",
          email_user: "nora.youssef@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1050,
          seat_user: 3,
          idTicket_user: 220002206,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 5,
          name_user: "يوسف علي",
          email_user: "youssef.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة العلوم السياسية",
          cost_user: 950,
          seat_user: 9,
          idTicket_user: 220002207,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 6,
          name_user: "ليلى أحمد",
          email_user: "laila.ahmed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفنون",
          cost_user: 1150,
          seat_user: 10,
          idTicket_user: 220002208,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 7,
          name_user: "محمود عبد الرحمن",
          email_user: "mahmoud.abdelrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الصيدلة",
          cost_user: 900,
          seat_user: 8,
          idTicket_user: 220002209,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 7,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 8,
          name_user: "مريم محمد",
          email_user: "maryam.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الهندسة المعمارية",
          cost_user: 1000,
          seat_user: 2,
          idTicket_user: 220002210,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 9,
          name_user: "أميرة علي",
          email_user: "amira.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الرياضيات",
          cost_user: 850,
          seat_user: 4,
          idTicket_user: 220002211,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 10,
          name_user: "أحمد أيمن",
          email_user: "ahmed.ayman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 1,
          idTicket_user: 220002212,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
      ],
    },
  },
  {
    id: 5,
    type: "حفلات تخرج",
    parties: {
      id_party: 5,
      type_party: "حفلات فان داي",
      name_party: "Fan Day Event",
      date_party: "الجمعة، 20 أغسطس 2024",
      location_party: "لندن، المملكة المتحدة",
      time_party: "2:00 بعد الظهر",
      users_party: [
        {
          id_user: 1,
          name_user: "سلمى محمود إبراهيم",
          email_user: "SalmaaAhmed12@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة كلية علوم",
          cost_user: 1000,
          seat_user: 5,
          idTicket_user: 220002203,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 2,
          name_user: "عبد الرحمن أحمد",
          email_user: "abdulrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1200,
          seat_user: 7,
          idTicket_user: 220002204,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 6,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 3,
          name_user: "أحمد محمد",
          email_user: "ahmed.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 6,
          idTicket_user: 220002205,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 4,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 4,
          name_user: "نورا يوسف",
          email_user: "nora.youssef@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1050,
          seat_user: 3,
          idTicket_user: 220002206,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 5,
          name_user: "يوسف علي",
          email_user: "youssef.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة العلوم السياسية",
          cost_user: 950,
          seat_user: 9,
          idTicket_user: 220002207,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 6,
          name_user: "ليلى أحمد",
          email_user: "laila.ahmed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفنون",
          cost_user: 1150,
          seat_user: 10,
          idTicket_user: 220002208,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 7,
          name_user: "محمود عبد الرحمن",
          email_user: "mahmoud.abdelrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الصيدلة",
          cost_user: 900,
          seat_user: 8,
          idTicket_user: 220002209,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 7,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 8,
          name_user: "مريم محمد",
          email_user: "maryam.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الهندسة المعمارية",
          cost_user: 1000,
          seat_user: 2,
          idTicket_user: 220002210,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 9,
          name_user: "أميرة علي",
          email_user: "amira.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الرياضيات",
          cost_user: 850,
          seat_user: 4,
          idTicket_user: 220002211,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 10,
          name_user: "أحمد أيمن",
          email_user: "ahmed.ayman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 1,
          idTicket_user: 220002212,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
      ],
    },
  },
  {
    id: 6,
    type: "حفلات تخرج",
    parties: {
      id_party: 6,
      type_party: "بازار",
      name_party: "Local Market",
      date_party: "السبت، 21 أغسطس 2024",
      location_party: "طوكيو، اليابان",
      time_party: "11:00 صباحًا",
      users_party: [
        {
          id_user: 1,
          name_user: "سلمى محمود إبراهيم",
          email_user: "SalmaaAhmed12@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة كلية علوم",
          cost_user: 1000,
          seat_user: 5,
          idTicket_user: 220002203,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 2,
          name_user: "عبد الرحمن أحمد",
          email_user: "abdulrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1200,
          seat_user: 7,
          idTicket_user: 220002204,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 6,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 3,
          name_user: "أحمد محمد",
          email_user: "ahmed.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 6,
          idTicket_user: 220002205,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 4,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 4,
          name_user: "نورا يوسف",
          email_user: "nora.youssef@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الطب",
          cost_user: 1050,
          seat_user: 3,
          idTicket_user: 220002206,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 5,
          name_user: "يوسف علي",
          email_user: "youssef.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة العلوم السياسية",
          cost_user: 950,
          seat_user: 9,
          idTicket_user: 220002207,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 6,
          name_user: "ليلى أحمد",
          email_user: "laila.ahmed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفنون",
          cost_user: 1150,
          seat_user: 10,
          idTicket_user: 220002208,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 7,
          name_user: "محمود عبد الرحمن",
          email_user: "mahmoud.abdelrahman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الصيدلة",
          cost_user: 900,
          seat_user: 8,
          idTicket_user: 220002209,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 7,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 8,
          name_user: "مريم محمد",
          email_user: "maryam.mohamed@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الهندسة المعمارية",
          cost_user: 1000,
          seat_user: 2,
          idTicket_user: 220002210,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 3,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 9,
          name_user: "أميرة علي",
          email_user: "amira.ali@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الرياضيات",
          cost_user: 850,
          seat_user: 4,
          idTicket_user: 220002211,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 5,
          date_user: "الاثنين، 16 أغسطس",
        },
        {
          id_user: 10,
          name_user: "أحمد أيمن",
          email_user: "ahmed.ayman@gmail.com",
          image_user: "https://i.ibb.co/8rC1tR9/team-03.png",
          party_user: "حفلة الفيزياء",
          cost_user: 1100,
          seat_user: 1,
          idTicket_user: 220002212,
          location_user: "روما، إيطاليا",
          numberOfCompanions_user: 2,
          date_user: "الاثنين، 16 أغسطس",
        },
      ],
    },
  },
];
// https://www.npoint.io/docs/bd48efeb2ee7716143c2
// https://api.npoint.io/bd48efeb2ee7716143c2
